# Generated by Django 5.1.1 on 2024-10-17 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_shippingaddress_customer_alter_order_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='customer',
            new_name='user',
        ),
    ]
